# Generated by Django 5.1.1 on 2024-10-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='coords_id',
            new_name='coords',
        ),
        migrations.RenameField(
            model_name='perevalimages',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='perevalimages',
            old_name='pereval_id',
            new_name='pereval',
        ),
    ]
