# Generated by Django 5.1.1 on 2024-10-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_rename_coords_id_perevaladded_coords_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerevalAreas',
        ),
        migrations.DeleteModel(
            name='SprActivitiesTypes',
        ),
    ]
