# Generated by Django 5.1.1 on 2024-10-07 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_delete_perevalareas_delete_spractivitiestypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevalimages',
            name='pereval',
        ),
        migrations.RemoveField(
            model_name='perevalimages',
            name='image',
        ),
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField()),
                ('beauty_title', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('other_titles', models.CharField(max_length=25)),
                ('connect', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('NE', 'новый'), ('PE', 'ожидается'), ('AC', 'принято'), ('RE', 'отклонено')], max_length=8)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.level')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='pereval',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pereval.pereval'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PerevalAdded',
        ),
        migrations.DeleteModel(
            name='PerevalImages',
        ),
    ]
