# Generated by Django 5.1.1 on 2024-10-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('NE', 'новый'), ('PE', 'ожидается'), ('AC', 'принято'), ('RE', 'отклонено')], default='NE', max_length=8),
        ),
    ]
