# Generated by Django 5.1.1 on 2024-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0007_alter_pereval_add_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='img',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='images',
            name='date_added',
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
    ]
