# Generated by Django 5.1.1 on 2024-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0008_rename_img_images_data_remove_images_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
