# Generated by Django 5.1.1 on 2024-10-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0010_pereval_creator_alter_images_pereval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pereval',
            old_name='creator',
            new_name='user',
        ),
    ]
