# Generated by Django 5.1.1 on 2024-10-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0011_rename_creator_pereval_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
